Repository lblod/frontend-mow-registry, pull requests merged in 2021-11, with the labels that each got.

#93 fixed bug where the change to the type of a newly created variable wasn't displayed
  app/components/traffic-measure/index.hbs
  app/components/traffic-measure/index.js
Labels: bug

#95 added ability to verify content
  app/components/content-check.hbs
  app/components/content-check.js
  app/components/traffic-measure/index.hbs
  app/models/concept.js
  app/styles/app.scss
  app/templates/road-marking-concepts/index.hbs
  app/templates/road-marking-concepts/road-marking-concept.hbs
  app/templates/road-sign-concepts/index.hbs
  app/templates/road-sign-concepts/road-sign-concept.hbs
  app/templates/traffic-light-concepts/index.hbs
  app/templates/traffic-light-concepts/traffic-light-concept.hbs
  app/templates/traffic-measure-concepts/index.hbs
  translations/en-us.yaml
  translations/nl-be.yaml
Labels: enhancement

#94 made instructions editable
  app/components/add-instruction.hbs
  app/components/instructions-table.hbs
  app/controllers/road-marking-concepts/road-marking-concept.js
  app/controllers/road-sign-concepts/road-sign-concept.js
  app/controllers/traffic-light-concepts/traffic-light-concept.js
  app/templates/road-marking-concepts/road-marking-concept.hbs
  app/templates/road-sign-concepts/road-sign-concept.hbs
  app/templates/traffic-light-concepts/traffic-light-concept.hbs
Labels: enhancement

#97 fix persisting signs/traffic lights/roadmarking
  app/templates/road-marking-concepts/edit.hbs
  app/templates/road-sign-concepts/edit.hbs
  app/templates/traffic-light-concepts/edit.hbs
Labels: bug

#98 Internal/refactor forms
  app/components/road-marking-form.hbs
  app/components/road-marking-form.js
  app/components/road-sign-form.hbs
  app/components/road-sign-form.js
  app/components/traffic-light-form.hbs
  app/components/traffic-light-form.js
  app/controllers/application.js
  app/controllers/road-marking-concepts/edit.js
  app/controllers/road-sign-concepts/edit.js
  app/controllers/traffic-light-concepts/edit.js
  app/routes/road-marking-concepts/new.js
  app/routes/road-sign-concepts/new.js
  app/routes/traffic-light-concepts/new.js
  app/templates/road-marking-concepts/edit.hbs
  app/templates/road-marking-concepts/new.hbs
  app/templates/road-sign-concepts/edit.hbs
  app/templates/road-sign-concepts/new.hbs
  app/templates/traffic-light-concepts/edit.hbs
  app/templates/traffic-light-concepts/new.hbs
Labels: bug, internal

#100 Chore/improve road markings
  CHANGELOG.md
  app/controllers/road-marking-concepts/road-marking-concept.js
  app/router.js
  app/services/codelists.js
  app/templates/road-marking-concepts/road-marking-concept.hbs
  app/templates/road-marking-concepts/road-marking-concept/instruction.hbs
  package-lock.json
  package.json
Labels: bug

#101 Bugfix/quality of life
  CHANGELOG.md
  app/components/add-instruction.js
  app/components/traffic-measure/index.hbs
  app/components/traffic-measure/index.js
  app/controllers/road-sign-concepts/road-sign-concept.js
  package-lock.json
  package.json
Labels: bug

#105 Code not displaying after refreshing
  app/components/traffic-measure/instruction-entry.hbs
  app/components/traffic-measure/instruction-entry.js
Labels: bug

#106 Fix measure relations not deleted properly
  app/components/traffic-measure/index.js
Labels: bug

#104 Add codelist management module
  app/components/codelist-form.hbs
  app/components/codelist-form.js
  app/components/compact-menu.hbs
  app/controllers/codelists-management/codelist.js
  app/controllers/codelists-management/edit.js
  app/controllers/codelists-management/index.js
  app/router.js
  app/routes/codelists-management.js
  app/routes/codelists-management/codelist.js
  app/routes/codelists-management/edit.js
  app/routes/codelists-management/index.js
  app/routes/codelists-management/new.js
  app/templates/codelists-management.hbs
  app/templates/codelists-management/codelist.hbs
  app/templates/codelists-management/edit-loading.hbs
  app/templates/codelists-management/edit.hbs
  app/templates/codelists-management/index.hbs
  app/templates/codelists-management/new.hbs
  app/templates/index.hbs
  app/validations/codelist.js
  package-lock.json
  translations/en-us.yaml
  translations/nl-be.yaml
Labels: enhancement

#103 feature: improved support for measures and linking instructions to measures
  app/components/add-instruction.js
  app/components/traffic-measure/add-sign.js
  app/components/traffic-measure/index.hbs
  app/components/traffic-measure/index.js
  app/components/traffic-measure/instruction-entry.hbs
  app/components/traffic-measure/sign-list.hbs
  app/helpers/truncate.js
  app/models/concept.js
  app/models/mapping.js
  app/models/template.js
  app/routes/traffic-measure-concepts/new.js
  translations/en-us.yaml
  translations/nl-be.yaml
Labels: enhancement
