Repository lblod/frontend-mow-registry, pull requests merged in 2022-01, with the labels that each got.

#119 Content check and design review
  app/components/traffic-measure/index.hbs
  app/controllers/login.js
  app/index.html
  app/templates/codelists-management/codelist.hbs
  app/templates/index.hbs
  app/templates/login.hbs
  config/environment.js
  public/assets/images/favicon.svg
  public/assets/images/header-1024.jpg
  public/assets/images/header-1600.jpg
  public/assets/images/header-320.jpg
  translations/en-us.yaml
  translations/nl-be.yaml
Labels: internal

#118 parsing improvements
  app/components/add-instruction.js
  app/components/traffic-measure/index.js
  app/services/codelists.js
Labels: enhancement

#120 Feature/date variables
  app/utils/include-mappings.js
Labels: enhancement

#122 Issue GN-3185: Bug on removing signs
  app/controllers/codelists-management/codelist.js
  app/controllers/road-marking-concepts/road-marking-concept.js
  app/controllers/road-sign-concepts/road-sign-concept.js
  app/controllers/traffic-light-concepts/traffic-light-concept.js
  app/routes/codelists-management/codelist.js
  app/templates/codelists-management/codelist.hbs
Labels: bug

#123 made measures appear fully unwrapped in preview
  app/components/traffic-measure-template.hbs
  app/components/traffic-measure-template.js
  app/components/traffic-measure/index.js
  app/routes/traffic-measure-concepts/index.js
  app/templates/traffic-measure-concepts/index.hbs
Labels: enhancement

#124 added tempura selector
  app/components/temporal-selector.hbs
  app/components/temporal-selector.js
  app/components/traffic-measure/index.hbs
  app/models/traffic-measure-concept.js
  translations/en-us.yaml
  translations/nl-be.yaml
Labels: enhancement

#126 Feature/configurable auth
  CHANGELOG.md
  config/environment.js
  package-lock.json
  package.json
Labels: enhancement
