Repository lblod/frontend-mow-registry, pull requests merged in 2024-09, with the labels that each got.

#274 Appuniversum v3
  app/components/add-instruction.hbs
  app/components/codelist-form.hbs
  app/components/content-check.hbs
  app/components/icon-catalog-form.hbs
  app/components/image-input.hbs
  app/components/page-loader.hbs
  app/components/road-marking-form.hbs
  app/components/road-sign-form.hbs
  app/components/road-sign/shape-select.hbs
  app/components/traffic-light-form.hbs
  app/components/traffic-measure/index.hbs
  app/components/traffic-measure/instruction-entry.hbs
  app/components/variable-signage-selector.hbs
  app/modifiers/auto-focus.ts
  app/styles/app.scss
  app/templates/application.hbs
  app/templates/codelists-management/edit-loading.hbs
  app/templates/codelists-management/index.hbs
  app/templates/icon-catalog/index.hbs
  app/templates/index-loading.hbs
  app/templates/loading.hbs
  app/templates/mock-login.hbs
  app/templates/road-marking-concepts/edit-loading.hbs
  app/templates/road-marking-concepts/index.hbs
  app/templates/road-marking-concepts/road-marking-concept.hbs
  app/templates/road-sign-concepts/edit-loading.hbs
  app/templates/road-sign-concepts/index.hbs
  app/templates/road-sign-concepts/road-sign-concept.hbs
  app/templates/traffic-light-concepts/edit-loading.hbs
  app/templates/traffic-light-concepts/index.hbs
  app/templates/traffic-light-concepts/traffic-light-concept.hbs
  app/templates/traffic-measure-concepts/edit-loading.hbs
  app/templates/traffic-measure-concepts/index.hbs
  config/environment.js
  ember-cli-build.js
  package-lock.json
  package.json
Labels: enhancement

#291 [GN-4966] fix variable cannot be saved
  app/components/traffic-measure-template.ts
  app/components/traffic-measure/index.hbs
  app/components/traffic-measure/index.ts
  app/models/variable.ts
Labels: bug

#296 [GN-5059] Set up Embroider
  app/modifiers/yasgui.ts
  app/router.ts
  app/templates/road-marking-concepts/road-marking-concept.hbs
  app/templates/road-sign-concepts/road-sign-concept.hbs
  app/templates/traffic-light-concepts/traffic-light-concept.hbs
  config/ember-cli-update.json
  ember-cli-build.js
  package-lock.json
  package.json
Labels: internal

#297 [GN-4967] Fix the logout url setup
  app/services/session.js
Labels: bug

#284 [GN-5030] Road signs module redesign
  .eslintrc.js
  app/components/add-instruction.js
  app/components/instruction-manager.hbs
  app/components/instruction-manager.js
  app/components/reactive-table.hbs
  app/components/related-roadmarkings-table.hbs
  app/components/related-roadsigns-table.hbs
  app/components/related-traffic-lights-table.hbs
  app/components/reset-filters.hbs
  app/components/road-sign-concept/header.hbs
  app/components/road-sign-concept/header.ts
  app/components/search-tables/road-sign.hbs
  app/components/sidebar-container.hbs
  app/components/sidebar-header.hbs
  app/components/sidebar-overlay-container.hbs
  app/components/validation-status.hbs
  app/controllers/road-sign-concepts/index.ts
  app/controllers/road-sign-concepts/road-sign-concept.ts
  app/controllers/road-sign-concepts/road-sign-concept/instructions/index.ts
  app/controllers/road-sign-concepts/road-sign-concept/main-signs.ts
  app/controllers/road-sign-concepts/road-sign-concept/related.ts
  app/controllers/road-sign-concepts/road-sign-concept/sub-signs.ts
  app/helpers/is-sub-sign.ts
  app/router.ts
  app/routes/road-sign-concepts/index.ts
  app/routes/road-sign-concepts/road-sign-concept.ts
  app/routes/road-sign-concepts/road-sign-concept/index.ts
  app/routes/road-sign-concepts/road-sign-concept/instructions/edit.ts
  app/routes/road-sign-concepts/road-sign-concept/instructions/index.ts
  app/routes/road-sign-concepts/road-sign-concept/main-signs.ts
  app/routes/road-sign-concepts/road-sign-concept/related.ts
  app/routes/road-sign-concepts/road-sign-concept/sub-signs.ts
  app/styles/_shame.scss
  app/styles/app.scss
  app/styles/components/_sidebar-container.scss
  app/styles/components/_sidebar-overlay-container.scss
  app/templates/road-sign-concepts/index.hbs
  app/templates/road-sign-concepts/road-sign-concept.hbs
  app/templates/road-sign-concepts/road-sign-concept/instruction.hbs
  app/templates/road-sign-concepts/road-sign-concept/instructions.hbs
  app/templates/road-sign-concepts/road-sign-concept/instructions/edit.hbs
  app/templates/road-sign-concepts/road-sign-concept/instructions/index.hbs
  app/templates/road-sign-concepts/road-sign-concept/main-signs.hbs
  app/templates/road-sign-concepts/road-sign-concept/related.hbs
  app/templates/road-sign-concepts/road-sign-concept/sub-signs.hbs
  translations/en-us.yaml
  translations/nl-be.yaml
Labels: enhancement

#293 [GN-5052] Road sign edit page improvements
  app/components/error-message.hbs
  app/components/image-input.hbs
  app/components/image-input.ts
  app/components/road-sign-form.hbs
  app/components/road-sign-form.ts
  app/components/road-sign-form/shape-manager.hbs
  app/components/road-sign-form/shape-manager.ts
  app/components/road-sign/shape-select.hbs
  app/components/road-sign/shape-select.ts
  app/helpers/sort-by-order.ts
  app/models/code-list.ts
  app/models/dimension.ts
  app/models/quantity-kind.ts
  app/models/road-sign-concept.ts
  app/models/unit.ts
  app/routes/road-sign-concepts/edit.ts
  app/routes/road-sign-concepts/new.ts
  app/templates/road-sign-concepts/edit.hbs
  app/templates/road-sign-concepts/new.hbs
  app/validators/schema.ts
  tests/unit/models/code-list-test.js
  tests/unit/models/road-marking-concept-test.js
  tests/unit/models/road-sign-concept-test.js
  tests/unit/models/traffic-light-concept-test.js
  translations/en-us.yaml
  translations/nl-be.yaml
Labels: enhancement

#299 Linting setup updates
  app/components/add-instruction.hbs
  app/components/codelist-form.hbs
  app/components/icon-catalog-form.hbs
  app/components/icon-select.hbs
  app/components/image-input.hbs
  app/components/instruction-manager.hbs
  app/components/reactive-table.hbs
  app/components/road-marking-form.hbs
  app/components/road-sign-form.hbs
  app/components/road-sign-form.ts
  app/components/road-sign-form/shape-manager.hbs
  app/components/road-sign-form/shape-manager.ts
  app/components/traffic-light-form.hbs
  app/components/traffic-measure-template.hbs
  app/components/traffic-measure/index.hbs
  app/components/traffic-measure/sign-list.hbs
  app/modifiers/auto-focus.ts
  app/routes/road-sign-concepts/road-sign-concept.ts
  app/routes/road-sign-concepts/road-sign-concept/instructions/edit.ts
  app/routes/road-sign-concepts/road-sign-concept/main-signs.ts
  app/routes/road-sign-concepts/road-sign-concept/related.ts
  app/routes/road-sign-concepts/road-sign-concept/sub-signs.ts
  app/services/file-service.ts
  package-lock.json
  package.json
Labels: internal
