Repository lblod/frontend-mow-registry, pull requests merged in 2025-02, with the labels that each got.

#313 Clean-up unused template annotation code
  .changeset/chilled-ladybugs-eat.md
  app/components/add-instruction.js
  app/components/traffic-measure/index.ts
  app/utils/include-variables.ts
Labels: internal

#314 variables: use `label` instead of `value`
  .changeset/fresh-mangos-thank.md
  app/components/add-instruction.hbs
  app/components/add-instruction.js
  app/components/instruction-manager.hbs
  app/components/road-sign-form/variable-manager.hbs
  app/components/road-sign-form/variable-manager.ts
  app/components/traffic-measure-template.ts
  app/components/traffic-measure/index.hbs
  app/components/traffic-measure/index.ts
  app/models/variable.ts
  app/templates/road-sign-concepts/road-sign-concept.hbs
Labels: enhancement

#317 Fix: variable name no longer changes on selecting variable type if it was modified before
  .changeset/strong-gorillas-begin.md
  app/components/road-sign-form/variable-manager.ts
Labels: bug

#310 AR-plichtig toggle
  .changeset/five-taxis-pretend.md
  app/components/ar-plichtig-status.hbs
  app/components/road-marking-form.hbs
  app/components/road-marking-form.ts
  app/components/road-sign-form.hbs
  app/components/road-sign-form.ts
  app/components/search-tables/road-marking.hbs
  app/components/search-tables/road-sign.hbs
  app/components/search-tables/traffic-light.hbs
  app/components/traffic-light-form.hbs
  app/components/traffic-light-form.ts
  app/controllers/road-marking-concepts/index.ts
  app/controllers/road-sign-concepts/index.ts
  app/controllers/traffic-light-concepts/index.ts
  app/models/traffic-sign-concept.ts
  app/routes/road-marking-concepts/index.ts
  app/routes/road-sign-concepts/index.ts
  app/routes/traffic-light-concepts/index.ts
  app/templates/road-marking-concepts/index.hbs
  app/templates/road-marking-concepts/road-marking-concept.hbs
  app/templates/road-sign-concepts/index.hbs
  app/templates/road-sign-concepts/road-sign-concept.hbs
  app/templates/traffic-light-concepts/index.hbs
  app/templates/traffic-light-concepts/traffic-light-concept.hbs
  app/utils/type-utils.ts
  translations/en-us.yaml
  translations/nl-be.yaml
Labels: enhancement
